// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 PowerTools contributors

import Foundation

struct FinderActionsStrings {
    // Settings and the Features hub
    let hubTitle: String
    let hubDescription: String
    let enableLabel: String
    let caption: String
    let extensionOn: String
    let extensionOff: String
    let openExtensionSettings: String
    // The menu inside Finder
    let menuRoot: String
    let groupCopyPath: String
    let copyFullPath: String
    let copyName: String
    let copyFolderPath: String
    let copyToShelf: String
    let openTerminal: String
    let groupNewFile: String
    let newTextFile: String
    let newMarkdownFile: String
    let newEmptyFile: String
    let compressZip: String
    let moveTo: String
    let copyTo: String
    let batchRename: String
    let deletePermanently: String
    let groupConvertImage: String
    let resizeImages: String
    let extractText: String
    let copyImage: String
    let editVideo: String
    let groupCompressVideo: String
    let compressVideoSmall: String
    let compressVideoEmail: String
    let compressVideoCustom: String
    let makeGIF: String
    let uninstallApp: String
    let installDiskImage: String
    // Feedback while running an action
    let copied: String
    let textCopied: String
    let noText: String
    let working: String
    let savedFormat: String       // + file name
    let failedFormat: String      // + reason
    let busy: String
    let mixedFolders: String
    let untitled: String
    let archive: String
    let moveButton: String
    let copyButton: String
    let moveMessage: String
    let copyMessage: String
    let deleteTitle: String
    let deleteBodyFormat: String  // + item names
    let deleteButton: String
    let cancel: String
    let featureOffFormat: String  // + feature name
    // Batch rename window
    let renameTitle: String
    let renameFind: String
    let renameReplace: String
    let renamePrefix: String
    let renameSuffix: String
    let renameNumbers: String
    let renameStart: String
    let renameButton: String
    let renameInvalid: String
    let renameDuplicate: String
    let renameTaken: String
}

extension FeatureStrings {
    static func finderActions(_ language: AppLanguage) -> FinderActionsStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension FinderActionsStrings {
    static let enUS = FinderActionsStrings(
        hubTitle: "Finder right-click menu",
        hubDescription: "Adds PowerTools AI actions to the right-click menu in Finder and on the desktop.",
        enableLabel: "Show PowerTools AI in the right-click menu",
        caption: "Right-click files, folders or the desktop and choose PowerTools AI. macOS keeps Finder extensions off until you allow them.",
        extensionOn: "The Finder extension is on",
        extensionOff: "The Finder extension is off in System Settings",
        openExtensionSettings: "Open Extension Settings…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Copy Path",
        copyFullPath: "Full Path",
        copyName: "Name",
        copyFolderPath: "Enclosing Folder Path",
        copyToShelf: "Copy to Shelf",
        openTerminal: "Open Terminal Here",
        groupNewFile: "New File Here",
        newTextFile: "Text File",
        newMarkdownFile: "Markdown File",
        newEmptyFile: "Empty File",
        compressZip: "Compress to Zip",
        moveTo: "Move to…",
        copyTo: "Copy to…",
        batchRename: "Batch Rename…",
        deletePermanently: "Delete Permanently…",
        groupConvertImage: "Convert Image",
        resizeImages: "Resize and Compress",
        extractText: "Extract Text",
        copyImage: "Copy Image",
        editVideo: "Trim and Edit Video…",
        groupCompressVideo: "Compress Video",
        compressVideoSmall: "Small (under 8 MB)",
        compressVideoEmail: "For Email (under 20 MB)",
        compressVideoCustom: "With My Media Settings",
        makeGIF: "Make GIF",
        uninstallApp: "Uninstall App…",
        installDiskImage: "Install App from Disk Image",
        copied: "Copied",
        textCopied: "Text copied",
        noText: "No text found",
        working: "Working…",
        savedFormat: "Saved %@",
        failedFormat: "Couldn’t finish: %@",
        busy: "Media is busy with another file",
        mixedFolders: "Choose items from a single folder",
        untitled: "untitled",
        archive: "Archive",
        moveButton: "Move",
        copyButton: "Copy",
        moveMessage: "Choose where to move the selected items.",
        copyMessage: "Choose where to copy the selected items.",
        deleteTitle: "Delete permanently?",
        deleteBodyFormat: "%@ will be removed right away without going to the Trash. This can’t be undone.",
        deleteButton: "Delete",
        cancel: "Cancel",
        featureOffFormat: "Turn on %@ in PowerTools AI first",
        renameTitle: "Batch Rename",
        renameFind: "Find",
        renameReplace: "Replace with",
        renamePrefix: "Add before name",
        renameSuffix: "Add after name",
        renameNumbers: "Add numbers",
        renameStart: "Start at",
        renameButton: "Rename",
        renameInvalid: "A name can’t be empty or contain / or :.",
        renameDuplicate: "Two items would end up with the same name.",
        renameTaken: "An item with that name is already in the folder."
    )

    static let ptBR = FinderActionsStrings(
        hubTitle: "Menu de clique direito do Finder",
        hubDescription: "Adiciona ações do PowerTools ao menu de clique direito no Finder e na mesa.",
        enableLabel: "Mostrar o PowerTools no menu de clique direito",
        caption: "Clique com o botão direito em arquivos, pastas ou na mesa e escolha PowerTools. O macOS mantém as extensões do Finder desativadas até você permitir.",
        extensionOn: "A extensão do Finder está ativada",
        extensionOff: "A extensão do Finder está desativada nos Ajustes do Sistema",
        openExtensionSettings: "Abrir Ajustes de Extensões…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Copiar Caminho",
        copyFullPath: "Caminho Completo",
        copyName: "Nome",
        copyFolderPath: "Caminho da Pasta",
        copyToShelf: "Copiar para a Área Temporária",
        openTerminal: "Abrir Terminal Aqui",
        groupNewFile: "Novo Arquivo Aqui",
        newTextFile: "Arquivo de Texto",
        newMarkdownFile: "Arquivo Markdown",
        newEmptyFile: "Arquivo Vazio",
        compressZip: "Comprimir em Zip",
        moveTo: "Mover para…",
        copyTo: "Copiar para…",
        batchRename: "Renomear em Lote…",
        deletePermanently: "Apagar Permanentemente…",
        groupConvertImage: "Converter Imagem",
        resizeImages: "Redimensionar e Comprimir",
        extractText: "Extrair Texto",
        copyImage: "Copiar Imagem",
        editVideo: "Cortar e Editar Vídeo…",
        groupCompressVideo: "Comprimir Vídeo",
        compressVideoSmall: "Pequeno (até 8 MB)",
        compressVideoEmail: "Para E-mail (até 20 MB)",
        compressVideoCustom: "Com Meus Ajustes de Media",
        makeGIF: "Criar GIF",
        uninstallApp: "Desinstalar App…",
        installDiskImage: "Instalar App da Imagem de Disco",
        copied: "Copiado",
        textCopied: "Texto copiado",
        noText: "Nenhum texto encontrado",
        working: "Processando…",
        savedFormat: "%@ salvo",
        failedFormat: "Não foi possível concluir: %@",
        busy: "A Media está ocupada com outro arquivo",
        mixedFolders: "Escolha itens de uma única pasta",
        untitled: "sem título",
        archive: "Arquivo",
        moveButton: "Mover",
        copyButton: "Copiar",
        moveMessage: "Escolha para onde mover os itens selecionados.",
        copyMessage: "Escolha para onde copiar os itens selecionados.",
        deleteTitle: "Apagar permanentemente?",
        deleteBodyFormat: "%@ será removido na hora, sem passar pelo Lixo. Não é possível desfazer.",
        deleteButton: "Apagar",
        cancel: "Cancelar",
        featureOffFormat: "Ative %@ no PowerTools primeiro",
        renameTitle: "Renomear em Lote",
        renameFind: "Procurar",
        renameReplace: "Substituir por",
        renamePrefix: "Adicionar antes do nome",
        renameSuffix: "Adicionar depois do nome",
        renameNumbers: "Adicionar números",
        renameStart: "Começar em",
        renameButton: "Renomear",
        renameInvalid: "Um nome não pode ficar vazio nem conter / ou :.",
        renameDuplicate: "Dois itens ficariam com o mesmo nome.",
        renameTaken: "Já existe um item com esse nome na pasta."
    )

    static let tr = FinderActionsStrings(
        hubTitle: "Finder sağ tık menüsü",
        hubDescription: "Finder’da ve masaüstünde sağ tık menüsüne PowerTools eylemleri ekler.",
        enableLabel: "PowerTools’u sağ tık menüsünde göster",
        caption: "Dosyalara, klasörlere veya masaüstüne sağ tıklayıp PowerTools’u seçin. macOS, siz izin verene kadar Finder uzantılarını kapalı tutar.",
        extensionOn: "Finder uzantısı açık",
        extensionOff: "Finder uzantısı Sistem Ayarları’nda kapalı",
        openExtensionSettings: "Uzantı Ayarlarını Aç…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Yolu Kopyala",
        copyFullPath: "Tam Yol",
        copyName: "Ad",
        copyFolderPath: "Klasör Yolu",
        copyToShelf: "Rafa Kopyala",
        openTerminal: "Terminal’i Burada Aç",
        groupNewFile: "Burada Yeni Dosya",
        newTextFile: "Metin Dosyası",
        newMarkdownFile: "Markdown Dosyası",
        newEmptyFile: "Boş Dosya",
        compressZip: "Zip Olarak Sıkıştır",
        moveTo: "Taşı…",
        copyTo: "Kopyala…",
        batchRename: "Toplu Yeniden Adlandır…",
        deletePermanently: "Kalıcı Olarak Sil…",
        groupConvertImage: "Görüntüyü Dönüştür",
        resizeImages: "Boyutlandır ve Sıkıştır",
        extractText: "Metni Çıkar",
        copyImage: "Görüntüyü Kopyala",
        editVideo: "Videoyu Kırp ve Düzenle…",
        groupCompressVideo: "Videoyu Sıkıştır",
        compressVideoSmall: "Küçük (8 MB altı)",
        compressVideoEmail: "E-posta için (20 MB altı)",
        compressVideoCustom: "Medya Ayarlarımla",
        makeGIF: "GIF Oluştur",
        uninstallApp: "Uygulamayı Kaldır…",
        installDiskImage: "Disk Görüntüsünden Uygulama Yükle",
        copied: "Kopyalandı",
        textCopied: "Metin kopyalandı",
        noText: "Metin bulunamadı",
        working: "İşleniyor…",
        savedFormat: "%@ kaydedildi",
        failedFormat: "Tamamlanamadı: %@",
        busy: "Medya başka bir dosyayla meşgul",
        mixedFolders: "Tek bir klasördeki öğeleri seçin",
        untitled: "adsız",
        archive: "Arşiv",
        moveButton: "Taşı",
        copyButton: "Kopyala",
        moveMessage: "Seçili öğelerin taşınacağı yeri seçin.",
        copyMessage: "Seçili öğelerin kopyalanacağı yeri seçin.",
        deleteTitle: "Kalıcı olarak silinsin mi?",
        deleteBodyFormat: "%@ Çöp Sepeti’ne gitmeden hemen silinecek. Bu işlem geri alınamaz.",
        deleteButton: "Sil",
        cancel: "İptal",
        featureOffFormat: "Önce PowerTools’ta %@ özelliğini açın",
        renameTitle: "Toplu Yeniden Adlandır",
        renameFind: "Bul",
        renameReplace: "Şununla değiştir",
        renamePrefix: "Adın önüne ekle",
        renameSuffix: "Adın sonuna ekle",
        renameNumbers: "Numara ekle",
        renameStart: "Başlangıç",
        renameButton: "Yeniden Adlandır",
        renameInvalid: "Ad boş olamaz ve / ya da : içeremez.",
        renameDuplicate: "İki öğe aynı adı alacak.",
        renameTaken: "Klasörde bu adda bir öğe zaten var."
    )

    static let ru = FinderActionsStrings(
        hubTitle: "Контекстное меню Finder",
        hubDescription: "Добавляет действия PowerTools в контекстное меню Finder и рабочего стола.",
        enableLabel: "Показывать PowerTools в контекстном меню",
        caption: "Нажмите правой кнопкой на файлы, папки или рабочий стол и выберите PowerTools. macOS держит расширения Finder выключенными, пока вы их не разрешите.",
        extensionOn: "Расширение Finder включено",
        extensionOff: "Расширение Finder выключено в Системных настройках",
        openExtensionSettings: "Открыть настройки расширений…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Скопировать путь",
        copyFullPath: "Полный путь",
        copyName: "Имя",
        copyFolderPath: "Путь к папке",
        copyToShelf: "Скопировать на полку",
        openTerminal: "Открыть Терминал здесь",
        groupNewFile: "Новый файл здесь",
        newTextFile: "Текстовый файл",
        newMarkdownFile: "Файл Markdown",
        newEmptyFile: "Пустой файл",
        compressZip: "Сжать в Zip",
        moveTo: "Переместить в…",
        copyTo: "Скопировать в…",
        batchRename: "Переименовать группу…",
        deletePermanently: "Удалить навсегда…",
        groupConvertImage: "Конвертировать изображение",
        resizeImages: "Изменить размер и сжать",
        extractText: "Извлечь текст",
        copyImage: "Скопировать изображение",
        editVideo: "Обрезать и редактировать видео…",
        groupCompressVideo: "Сжать видео",
        compressVideoSmall: "Маленькое (до 8 МБ)",
        compressVideoEmail: "Для почты (до 20 МБ)",
        compressVideoCustom: "С моими настройками медиа",
        makeGIF: "Создать GIF",
        uninstallApp: "Удалить приложение…",
        installDiskImage: "Установить приложение из образа диска",
        copied: "Скопировано",
        textCopied: "Текст скопирован",
        noText: "Текст не найден",
        working: "Обработка…",
        savedFormat: "Сохранено: %@",
        failedFormat: "Не удалось завершить: %@",
        busy: "Медиа занято другим файлом",
        mixedFolders: "Выберите объекты из одной папки",
        untitled: "без названия",
        archive: "Архив",
        moveButton: "Переместить",
        copyButton: "Скопировать",
        moveMessage: "Выберите, куда переместить выбранные объекты.",
        copyMessage: "Выберите, куда скопировать выбранные объекты.",
        deleteTitle: "Удалить навсегда?",
        deleteBodyFormat: "%@: объекты будут удалены сразу, минуя Корзину. Это действие нельзя отменить.",
        deleteButton: "Удалить",
        cancel: "Отмена",
        featureOffFormat: "Сначала включите «%@» в PowerTools",
        renameTitle: "Переименование группы",
        renameFind: "Найти",
        renameReplace: "Заменить на",
        renamePrefix: "Добавить перед именем",
        renameSuffix: "Добавить после имени",
        renameNumbers: "Добавить номера",
        renameStart: "Начать с",
        renameButton: "Переименовать",
        renameInvalid: "Имя не может быть пустым или содержать / или :.",
        renameDuplicate: "Два объекта получат одинаковое имя.",
        renameTaken: "В папке уже есть объект с таким именем."
    )

    static let es = FinderActionsStrings(
        hubTitle: "Menú contextual del Finder",
        hubDescription: "Añade acciones de PowerTools al menú contextual del Finder y del escritorio.",
        enableLabel: "Mostrar PowerTools en el menú contextual",
        caption: "Haz clic derecho en archivos, carpetas o el escritorio y elige PowerTools. macOS mantiene desactivadas las extensiones del Finder hasta que las permitas.",
        extensionOn: "La extensión del Finder está activada",
        extensionOff: "La extensión del Finder está desactivada en Ajustes del Sistema",
        openExtensionSettings: "Abrir ajustes de extensiones…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Copiar ruta",
        copyFullPath: "Ruta completa",
        copyName: "Nombre",
        copyFolderPath: "Ruta de la carpeta",
        copyToShelf: "Copiar al estante",
        openTerminal: "Abrir Terminal aquí",
        groupNewFile: "Nuevo archivo aquí",
        newTextFile: "Archivo de texto",
        newMarkdownFile: "Archivo Markdown",
        newEmptyFile: "Archivo vacío",
        compressZip: "Comprimir en Zip",
        moveTo: "Mover a…",
        copyTo: "Copiar a…",
        batchRename: "Renombrar en lote…",
        deletePermanently: "Eliminar permanentemente…",
        groupConvertImage: "Convertir imagen",
        resizeImages: "Redimensionar y comprimir",
        extractText: "Extraer texto",
        copyImage: "Copiar imagen",
        editVideo: "Recortar y editar vídeo…",
        groupCompressVideo: "Comprimir vídeo",
        compressVideoSmall: "Pequeño (menos de 8 MB)",
        compressVideoEmail: "Para correo (menos de 20 MB)",
        compressVideoCustom: "Con mis ajustes de Media",
        makeGIF: "Crear GIF",
        uninstallApp: "Desinstalar app…",
        installDiskImage: "Instalar app desde imagen de disco",
        copied: "Copiado",
        textCopied: "Texto copiado",
        noText: "No se encontró texto",
        working: "Procesando…",
        savedFormat: "%@ guardado",
        failedFormat: "No se pudo terminar: %@",
        busy: "Media está ocupada con otro archivo",
        mixedFolders: "Elige elementos de una sola carpeta",
        untitled: "sin título",
        archive: "Archivo",
        moveButton: "Mover",
        copyButton: "Copiar",
        moveMessage: "Elige dónde mover los elementos seleccionados.",
        copyMessage: "Elige dónde copiar los elementos seleccionados.",
        deleteTitle: "¿Eliminar permanentemente?",
        deleteBodyFormat: "%@ se eliminará al momento, sin pasar por la Papelera. No se puede deshacer.",
        deleteButton: "Eliminar",
        cancel: "Cancelar",
        featureOffFormat: "Activa %@ en PowerTools primero",
        renameTitle: "Renombrar en lote",
        renameFind: "Buscar",
        renameReplace: "Reemplazar por",
        renamePrefix: "Añadir antes del nombre",
        renameSuffix: "Añadir después del nombre",
        renameNumbers: "Añadir números",
        renameStart: "Empezar en",
        renameButton: "Renombrar",
        renameInvalid: "Un nombre no puede estar vacío ni contener / o :.",
        renameDuplicate: "Dos elementos acabarían con el mismo nombre.",
        renameTaken: "Ya hay un elemento con ese nombre en la carpeta."
    )

    static let de = FinderActionsStrings(
        hubTitle: "Finder-Kontextmenü",
        hubDescription: "Fügt PowerTools-Aktionen zum Kontextmenü im Finder und auf dem Schreibtisch hinzu.",
        enableLabel: "PowerTools im Kontextmenü anzeigen",
        caption: "Klicke mit der rechten Maustaste auf Dateien, Ordner oder den Schreibtisch und wähle PowerTools. macOS lässt Finder-Erweiterungen aus, bis du sie erlaubst.",
        extensionOn: "Die Finder-Erweiterung ist aktiv",
        extensionOff: "Die Finder-Erweiterung ist in den Systemeinstellungen deaktiviert",
        openExtensionSettings: "Erweiterungseinstellungen öffnen …",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Pfad kopieren",
        copyFullPath: "Vollständiger Pfad",
        copyName: "Name",
        copyFolderPath: "Ordnerpfad",
        copyToShelf: "In die Ablage kopieren",
        openTerminal: "Terminal hier öffnen",
        groupNewFile: "Neue Datei hier",
        newTextFile: "Textdatei",
        newMarkdownFile: "Markdown-Datei",
        newEmptyFile: "Leere Datei",
        compressZip: "Als Zip komprimieren",
        moveTo: "Bewegen nach …",
        copyTo: "Kopieren nach …",
        batchRename: "Stapelweise umbenennen …",
        deletePermanently: "Endgültig löschen …",
        groupConvertImage: "Bild konvertieren",
        resizeImages: "Skalieren und komprimieren",
        extractText: "Text extrahieren",
        copyImage: "Bild kopieren",
        editVideo: "Video kürzen und bearbeiten …",
        groupCompressVideo: "Video komprimieren",
        compressVideoSmall: "Klein (unter 8 MB)",
        compressVideoEmail: "Für E-Mail (unter 20 MB)",
        compressVideoCustom: "Mit meinen Medien-Einstellungen",
        makeGIF: "GIF erstellen",
        uninstallApp: "App deinstallieren …",
        installDiskImage: "App aus Image installieren",
        copied: "Kopiert",
        textCopied: "Text kopiert",
        noText: "Kein Text gefunden",
        working: "Wird bearbeitet …",
        savedFormat: "%@ gesichert",
        failedFormat: "Konnte nicht abgeschlossen werden: %@",
        busy: "Medien bearbeitet gerade eine andere Datei",
        mixedFolders: "Wähle Objekte aus nur einem Ordner",
        untitled: "Ohne Titel",
        archive: "Archiv",
        moveButton: "Bewegen",
        copyButton: "Kopieren",
        moveMessage: "Wähle, wohin die ausgewählten Objekte bewegt werden.",
        copyMessage: "Wähle, wohin die ausgewählten Objekte kopiert werden.",
        deleteTitle: "Endgültig löschen?",
        deleteBodyFormat: "%@ wird sofort entfernt, ohne im Papierkorb zu landen. Das kann nicht widerrufen werden.",
        deleteButton: "Löschen",
        cancel: "Abbrechen",
        featureOffFormat: "Aktiviere zuerst %@ in PowerTools",
        renameTitle: "Stapelweise umbenennen",
        renameFind: "Suchen",
        renameReplace: "Ersetzen durch",
        renamePrefix: "Vor dem Namen einfügen",
        renameSuffix: "Nach dem Namen einfügen",
        renameNumbers: "Nummern hinzufügen",
        renameStart: "Beginnen bei",
        renameButton: "Umbenennen",
        renameInvalid: "Ein Name darf nicht leer sein und kein / oder : enthalten.",
        renameDuplicate: "Zwei Objekte hätten denselben Namen.",
        renameTaken: "Im Ordner gibt es bereits ein Objekt mit diesem Namen."
    )

    static let fr = FinderActionsStrings(
        hubTitle: "Menu contextuel du Finder",
        hubDescription: "Ajoute des actions PowerTools au menu contextuel du Finder et du bureau.",
        enableLabel: "Afficher PowerTools dans le menu contextuel",
        caption: "Faites un clic droit sur des fichiers, des dossiers ou le bureau et choisissez PowerTools. macOS laisse les extensions du Finder désactivées jusqu’à ce que vous les autorisiez.",
        extensionOn: "L’extension du Finder est activée",
        extensionOff: "L’extension du Finder est désactivée dans Réglages Système",
        openExtensionSettings: "Ouvrir les réglages des extensions…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Copier le chemin",
        copyFullPath: "Chemin complet",
        copyName: "Nom",
        copyFolderPath: "Chemin du dossier",
        copyToShelf: "Copier sur l’étagère",
        openTerminal: "Ouvrir Terminal ici",
        groupNewFile: "Nouveau fichier ici",
        newTextFile: "Fichier texte",
        newMarkdownFile: "Fichier Markdown",
        newEmptyFile: "Fichier vide",
        compressZip: "Compresser en Zip",
        moveTo: "Déplacer vers…",
        copyTo: "Copier vers…",
        batchRename: "Renommer par lot…",
        deletePermanently: "Supprimer définitivement…",
        groupConvertImage: "Convertir l’image",
        resizeImages: "Redimensionner et compresser",
        extractText: "Extraire le texte",
        copyImage: "Copier l’image",
        editVideo: "Couper et modifier la vidéo…",
        groupCompressVideo: "Compresser la vidéo",
        compressVideoSmall: "Petite (moins de 8 Mo)",
        compressVideoEmail: "Pour e-mail (moins de 20 Mo)",
        compressVideoCustom: "Avec mes réglages Médias",
        makeGIF: "Créer un GIF",
        uninstallApp: "Désinstaller l’app…",
        installDiskImage: "Installer l’app depuis l’image disque",
        copied: "Copié",
        textCopied: "Texte copié",
        noText: "Aucun texte trouvé",
        working: "Traitement…",
        savedFormat: "%@ enregistré",
        failedFormat: "Impossible de terminer\u{00A0}: %@",
        busy: "Médias traite déjà un autre fichier",
        mixedFolders: "Choisissez des éléments d’un seul dossier",
        untitled: "sans titre",
        archive: "Archive",
        moveButton: "Déplacer",
        copyButton: "Copier",
        moveMessage: "Choisissez où déplacer les éléments sélectionnés.",
        copyMessage: "Choisissez où copier les éléments sélectionnés.",
        deleteTitle: "Supprimer définitivement\u{00A0}?",
        deleteBodyFormat: "%@ sera supprimé tout de suite, sans passer par la corbeille. Cette action est irréversible.",
        deleteButton: "Supprimer",
        cancel: "Annuler",
        featureOffFormat: "Activez d’abord %@ dans PowerTools",
        renameTitle: "Renommer par lot",
        renameFind: "Rechercher",
        renameReplace: "Remplacer par",
        renamePrefix: "Ajouter avant le nom",
        renameSuffix: "Ajouter après le nom",
        renameNumbers: "Ajouter des numéros",
        renameStart: "Commencer à",
        renameButton: "Renommer",
        renameInvalid: "Un nom ne peut pas être vide ni contenir / ou\u{00A0}:.",
        renameDuplicate: "Deux éléments auraient le même nom.",
        renameTaken: "Un élément porte déjà ce nom dans le dossier."
    )

    static let it = FinderActionsStrings(
        hubTitle: "Menu contestuale del Finder",
        hubDescription: "Aggiunge azioni di PowerTools al menu contestuale del Finder e della scrivania.",
        enableLabel: "Mostra PowerTools nel menu contestuale",
        caption: "Fai clic destro su file, cartelle o sulla scrivania e scegli PowerTools. macOS tiene disattivate le estensioni del Finder finché non le consenti.",
        extensionOn: "L’estensione del Finder è attiva",
        extensionOff: "L’estensione del Finder è disattivata in Impostazioni di Sistema",
        openExtensionSettings: "Apri impostazioni estensioni…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "Copia percorso",
        copyFullPath: "Percorso completo",
        copyName: "Nome",
        copyFolderPath: "Percorso della cartella",
        copyToShelf: "Copia sul ripiano",
        openTerminal: "Apri Terminale qui",
        groupNewFile: "Nuovo file qui",
        newTextFile: "File di testo",
        newMarkdownFile: "File Markdown",
        newEmptyFile: "File vuoto",
        compressZip: "Comprimi in Zip",
        moveTo: "Sposta in…",
        copyTo: "Copia in…",
        batchRename: "Rinomina in blocco…",
        deletePermanently: "Elimina definitivamente…",
        groupConvertImage: "Converti immagine",
        resizeImages: "Ridimensiona e comprimi",
        extractText: "Estrai testo",
        copyImage: "Copia immagine",
        editVideo: "Taglia e modifica video…",
        groupCompressVideo: "Comprimi video",
        compressVideoSmall: "Piccolo (meno di 8 MB)",
        compressVideoEmail: "Per e-mail (meno di 20 MB)",
        compressVideoCustom: "Con le mie impostazioni Media",
        makeGIF: "Crea GIF",
        uninstallApp: "Disinstalla app…",
        installDiskImage: "Installa app dall’immagine disco",
        copied: "Copiato",
        textCopied: "Testo copiato",
        noText: "Nessun testo trovato",
        working: "Elaborazione…",
        savedFormat: "%@ salvato",
        failedFormat: "Impossibile completare: %@",
        busy: "Media è occupato con un altro file",
        mixedFolders: "Scegli elementi da una sola cartella",
        untitled: "senza titolo",
        archive: "Archivio",
        moveButton: "Sposta",
        copyButton: "Copia",
        moveMessage: "Scegli dove spostare gli elementi selezionati.",
        copyMessage: "Scegli dove copiare gli elementi selezionati.",
        deleteTitle: "Eliminare definitivamente?",
        deleteBodyFormat: "%@ verrà rimosso subito, senza passare dal Cestino. L’operazione non si può annullare.",
        deleteButton: "Elimina",
        cancel: "Annulla",
        featureOffFormat: "Attiva prima %@ in PowerTools",
        renameTitle: "Rinomina in blocco",
        renameFind: "Trova",
        renameReplace: "Sostituisci con",
        renamePrefix: "Aggiungi prima del nome",
        renameSuffix: "Aggiungi dopo il nome",
        renameNumbers: "Aggiungi numeri",
        renameStart: "Inizia da",
        renameButton: "Rinomina",
        renameInvalid: "Un nome non può essere vuoto né contenere / o :.",
        renameDuplicate: "Due elementi avrebbero lo stesso nome.",
        renameTaken: "Nella cartella c’è già un elemento con quel nome."
    )

    static let ja = FinderActionsStrings(
        hubTitle: "Finderの右クリックメニュー",
        hubDescription: "FinderとデスクトップのコンテキストメニューにPowerToolsのアクションを追加します。",
        enableLabel: "右クリックメニューにPowerToolsを表示",
        caption: "ファイル、フォルダ、またはデスクトップを右クリックしてPowerToolsを選びます。macOSでは、許可するまでFinder機能拡張はオフのままです。",
        extensionOn: "Finder機能拡張はオンです",
        extensionOff: "Finder機能拡張はシステム設定でオフになっています",
        openExtensionSettings: "機能拡張の設定を開く…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "パスをコピー",
        copyFullPath: "フルパス",
        copyName: "名前",
        copyFolderPath: "フォルダのパス",
        copyToShelf: "シェルフにコピー",
        openTerminal: "ここでターミナルを開く",
        groupNewFile: "ここに新規ファイル",
        newTextFile: "テキストファイル",
        newMarkdownFile: "Markdownファイル",
        newEmptyFile: "空のファイル",
        compressZip: "Zipに圧縮",
        moveTo: "移動…",
        copyTo: "コピー…",
        batchRename: "一括で名前を変更…",
        deletePermanently: "完全に削除…",
        groupConvertImage: "イメージを変換",
        resizeImages: "サイズ変更と圧縮",
        extractText: "テキストを抽出",
        copyImage: "イメージをコピー",
        editVideo: "ビデオをトリミング・編集…",
        groupCompressVideo: "ビデオを圧縮",
        compressVideoSmall: "小（8 MB未満）",
        compressVideoEmail: "メール用（20 MB未満）",
        compressVideoCustom: "メディアの設定を使用",
        makeGIF: "GIFを作成",
        uninstallApp: "アプリをアンインストール…",
        installDiskImage: "ディスクイメージからアプリをインストール",
        copied: "コピーしました",
        textCopied: "テキストをコピーしました",
        noText: "テキストが見つかりません",
        working: "処理中…",
        savedFormat: "%@を保存しました",
        failedFormat: "完了できませんでした: %@",
        busy: "メディアは別のファイルを処理中です",
        mixedFolders: "1つのフォルダ内の項目を選んでください",
        untitled: "名称未設定",
        archive: "アーカイブ",
        moveButton: "移動",
        copyButton: "コピー",
        moveMessage: "選択した項目の移動先を選んでください。",
        copyMessage: "選択した項目のコピー先を選んでください。",
        deleteTitle: "完全に削除しますか？",
        deleteBodyFormat: "%@はゴミ箱に入らず、すぐに削除されます。この操作は取り消せません。",
        deleteButton: "削除",
        cancel: "キャンセル",
        featureOffFormat: "先にPowerToolsで%@をオンにしてください",
        renameTitle: "一括で名前を変更",
        renameFind: "検索",
        renameReplace: "置き換え",
        renamePrefix: "名前の前に追加",
        renameSuffix: "名前の後に追加",
        renameNumbers: "番号を追加",
        renameStart: "開始番号",
        renameButton: "名前を変更",
        renameInvalid: "名前は空にできず、/や:を含められません。",
        renameDuplicate: "2つの項目が同じ名前になります。",
        renameTaken: "同じ名前の項目がフォルダに既にあります。"
    )

    static let ko = FinderActionsStrings(
        hubTitle: "Finder 오른쪽 클릭 메뉴",
        hubDescription: "Finder와 데스크탑의 오른쪽 클릭 메뉴에 PowerTools 동작을 추가합니다.",
        enableLabel: "오른쪽 클릭 메뉴에 PowerTools 표시",
        caption: "파일, 폴더 또는 데스크탑을 오른쪽 클릭하고 PowerTools를 선택하세요. macOS는 허용하기 전까지 Finder 확장 프로그램을 꺼 둡니다.",
        extensionOn: "Finder 확장 프로그램이 켜져 있습니다",
        extensionOff: "시스템 설정에서 Finder 확장 프로그램이 꺼져 있습니다",
        openExtensionSettings: "확장 프로그램 설정 열기…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "경로 복사",
        copyFullPath: "전체 경로",
        copyName: "이름",
        copyFolderPath: "폴더 경로",
        copyToShelf: "선반에 복사",
        openTerminal: "여기에서 터미널 열기",
        groupNewFile: "여기에 새 파일",
        newTextFile: "텍스트 파일",
        newMarkdownFile: "Markdown 파일",
        newEmptyFile: "빈 파일",
        compressZip: "Zip으로 압축",
        moveTo: "이동…",
        copyTo: "복사…",
        batchRename: "일괄 이름 변경…",
        deletePermanently: "영구적으로 삭제…",
        groupConvertImage: "이미지 변환",
        resizeImages: "크기 조절 및 압축",
        extractText: "텍스트 추출",
        copyImage: "이미지 복사",
        editVideo: "비디오 다듬기 및 편집…",
        groupCompressVideo: "비디오 압축",
        compressVideoSmall: "작게 (8MB 미만)",
        compressVideoEmail: "이메일용 (20MB 미만)",
        compressVideoCustom: "내 미디어 설정으로",
        makeGIF: "GIF 만들기",
        uninstallApp: "앱 제거…",
        installDiskImage: "디스크 이미지에서 앱 설치",
        copied: "복사됨",
        textCopied: "텍스트 복사됨",
        noText: "텍스트를 찾을 수 없음",
        working: "처리 중…",
        savedFormat: "%@ 저장됨",
        failedFormat: "완료하지 못했습니다: %@",
        busy: "미디어가 다른 파일을 처리하고 있습니다",
        mixedFolders: "한 폴더에 있는 항목을 선택하세요",
        untitled: "제목 없음",
        archive: "아카이브",
        moveButton: "이동",
        copyButton: "복사",
        moveMessage: "선택한 항목을 이동할 위치를 선택하세요.",
        copyMessage: "선택한 항목을 복사할 위치를 선택하세요.",
        deleteTitle: "영구적으로 삭제하겠습니까?",
        deleteBodyFormat: "%@ 항목이 휴지통을 거치지 않고 즉시 삭제됩니다. 이 작업은 취소할 수 없습니다.",
        deleteButton: "삭제",
        cancel: "취소",
        featureOffFormat: "먼저 PowerTools에서 %@ 기능을 켜세요",
        renameTitle: "일괄 이름 변경",
        renameFind: "찾기",
        renameReplace: "다음으로 대치",
        renamePrefix: "이름 앞에 추가",
        renameSuffix: "이름 뒤에 추가",
        renameNumbers: "번호 추가",
        renameStart: "시작 번호",
        renameButton: "이름 변경",
        renameInvalid: "이름은 비워 둘 수 없으며 / 또는 :를 포함할 수 없습니다.",
        renameDuplicate: "두 항목의 이름이 같아집니다.",
        renameTaken: "폴더에 같은 이름의 항목이 이미 있습니다."
    )

    static let zhHans = FinderActionsStrings(
        hubTitle: "访达右键菜单",
        hubDescription: "在访达和桌面的右键菜单中添加 PowerTools 操作。",
        enableLabel: "在右键菜单中显示 PowerTools",
        caption: "右键点按文件、文件夹或桌面，然后选取 PowerTools。在你允许之前，macOS 会让访达扩展保持关闭。",
        extensionOn: "访达扩展已开启",
        extensionOff: "访达扩展在系统设置中已关闭",
        openExtensionSettings: "打开扩展设置…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "拷贝路径",
        copyFullPath: "完整路径",
        copyName: "名称",
        copyFolderPath: "文件夹路径",
        copyToShelf: "拷贝到暂存架",
        openTerminal: "在此处打开终端",
        groupNewFile: "在此处新建文件",
        newTextFile: "文本文件",
        newMarkdownFile: "Markdown 文件",
        newEmptyFile: "空文件",
        compressZip: "压缩为 Zip",
        moveTo: "移动到…",
        copyTo: "拷贝到…",
        batchRename: "批量重新命名…",
        deletePermanently: "永久删除…",
        groupConvertImage: "转换图像",
        resizeImages: "调整大小并压缩",
        extractText: "提取文本",
        copyImage: "拷贝图像",
        editVideo: "修剪和编辑视频…",
        groupCompressVideo: "压缩视频",
        compressVideoSmall: "小（小于 8 MB）",
        compressVideoEmail: "用于邮件（小于 20 MB）",
        compressVideoCustom: "使用我的媒体设置",
        makeGIF: "制作 GIF",
        uninstallApp: "卸载 App…",
        installDiskImage: "从磁盘映像安装 App",
        copied: "已拷贝",
        textCopied: "文本已拷贝",
        noText: "未找到文本",
        working: "正在处理…",
        savedFormat: "已存储 %@",
        failedFormat: "无法完成：%@",
        busy: "媒体正在处理另一个文件",
        mixedFolders: "请选择同一文件夹中的项目",
        untitled: "未命名",
        archive: "归档",
        moveButton: "移动",
        copyButton: "拷贝",
        moveMessage: "选择要将所选项目移到的位置。",
        copyMessage: "选择要将所选项目拷贝到的位置。",
        deleteTitle: "要永久删除吗？",
        deleteBodyFormat: "%@ 将立即删除，不会进入废纸篓。此操作无法撤销。",
        deleteButton: "删除",
        cancel: "取消",
        featureOffFormat: "请先在 PowerTools 中开启“%@”",
        renameTitle: "批量重新命名",
        renameFind: "查找",
        renameReplace: "替换为",
        renamePrefix: "添加到名称前",
        renameSuffix: "添加到名称后",
        renameNumbers: "添加编号",
        renameStart: "起始编号",
        renameButton: "重新命名",
        renameInvalid: "名称不能为空，也不能包含 / 或 :。",
        renameDuplicate: "两个项目将使用相同的名称。",
        renameTaken: "文件夹中已有同名项目。"
    )

    static let zhTW = FinderActionsStrings(
        hubTitle: "Finder 右鍵選單",
        hubDescription: "在 Finder 和桌面的右鍵選單中加入 PowerTools 動作。",
        enableLabel: "在右鍵選單中顯示 PowerTools",
        caption: "在檔案、檔案夾或桌面上按右鍵，然後選擇 PowerTools。在你允許之前，macOS 會讓 Finder 延伸功能保持關閉。",
        extensionOn: "Finder 延伸功能已開啟",
        extensionOff: "Finder 延伸功能在系統設定中已關閉",
        openExtensionSettings: "打開延伸功能設定…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "拷貝路徑",
        copyFullPath: "完整路徑",
        copyName: "名稱",
        copyFolderPath: "檔案夾路徑",
        copyToShelf: "拷貝到暫存架",
        openTerminal: "在此打開終端機",
        groupNewFile: "在此新增檔案",
        newTextFile: "文字檔案",
        newMarkdownFile: "Markdown 檔案",
        newEmptyFile: "空白檔案",
        compressZip: "壓縮為 Zip",
        moveTo: "搬移到…",
        copyTo: "拷貝到…",
        batchRename: "批次重新命名…",
        deletePermanently: "永久刪除…",
        groupConvertImage: "轉換影像",
        resizeImages: "調整大小並壓縮",
        extractText: "擷取文字",
        copyImage: "拷貝影像",
        editVideo: "修剪和編輯影片…",
        groupCompressVideo: "壓縮影片",
        compressVideoSmall: "小（小於 8 MB）",
        compressVideoEmail: "用於郵件（小於 20 MB）",
        compressVideoCustom: "使用我的媒體設定",
        makeGIF: "製作 GIF",
        uninstallApp: "解除安裝 App…",
        installDiskImage: "從磁碟映像檔安裝 App",
        copied: "已拷貝",
        textCopied: "文字已拷貝",
        noText: "找不到文字",
        working: "處理中…",
        savedFormat: "已儲存 %@",
        failedFormat: "無法完成：%@",
        busy: "媒體正在處理另一個檔案",
        mixedFolders: "請選擇同一檔案夾中的項目",
        untitled: "未命名",
        archive: "封存",
        moveButton: "搬移",
        copyButton: "拷貝",
        moveMessage: "選擇要將所選項目搬移到的位置。",
        copyMessage: "選擇要將所選項目拷貝到的位置。",
        deleteTitle: "要永久刪除嗎？",
        deleteBodyFormat: "%@ 將立即刪除，不會移到垃圾桶。此動作無法還原。",
        deleteButton: "刪除",
        cancel: "取消",
        featureOffFormat: "請先在 PowerTools 中開啟「%@」",
        renameTitle: "批次重新命名",
        renameFind: "尋找",
        renameReplace: "取代為",
        renamePrefix: "加在名稱前",
        renameSuffix: "加在名稱後",
        renameNumbers: "加入編號",
        renameStart: "起始編號",
        renameButton: "重新命名",
        renameInvalid: "名稱不可為空白，也不可包含 / 或 :。",
        renameDuplicate: "兩個項目會使用相同的名稱。",
        renameTaken: "檔案夾中已有同名項目。"
    )

    static let zhHK = FinderActionsStrings(
        hubTitle: "Finder 右鍵選單",
        hubDescription: "在 Finder 和桌面的右鍵選單中加入 PowerTools 動作。",
        enableLabel: "在右鍵選單中顯示 PowerTools",
        caption: "在檔案、資料夾或桌面上按右鍵，然後選擇 PowerTools。在你允許之前，macOS 會讓 Finder 延伸功能保持關閉。",
        extensionOn: "Finder 延伸功能已開啟",
        extensionOff: "Finder 延伸功能在系統設定中已關閉",
        openExtensionSettings: "打開延伸功能設定…",
        menuRoot: "PowerTools AI",
        groupCopyPath: "拷貝路徑",
        copyFullPath: "完整路徑",
        copyName: "名稱",
        copyFolderPath: "資料夾路徑",
        copyToShelf: "拷貝到暫存架",
        openTerminal: "在此打開終端機",
        groupNewFile: "在此新增檔案",
        newTextFile: "文字檔案",
        newMarkdownFile: "Markdown 檔案",
        newEmptyFile: "空白檔案",
        compressZip: "壓縮為 Zip",
        moveTo: "移動到…",
        copyTo: "拷貝到…",
        batchRename: "批次重新命名…",
        deletePermanently: "永久刪除…",
        groupConvertImage: "轉換影像",
        resizeImages: "調整大小並壓縮",
        extractText: "擷取文字",
        copyImage: "拷貝影像",
        editVideo: "修剪和編輯影片…",
        groupCompressVideo: "壓縮影片",
        compressVideoSmall: "小（少於 8 MB）",
        compressVideoEmail: "用於電郵（少於 20 MB）",
        compressVideoCustom: "使用我的媒體設定",
        makeGIF: "製作 GIF",
        uninstallApp: "解除安裝 App…",
        installDiskImage: "從磁碟映像檔安裝 App",
        copied: "已拷貝",
        textCopied: "文字已拷貝",
        noText: "找不到文字",
        working: "處理中…",
        savedFormat: "已儲存 %@",
        failedFormat: "無法完成：%@",
        busy: "媒體正在處理另一個檔案",
        mixedFolders: "請選擇同一資料夾中的項目",
        untitled: "未命名",
        archive: "封存",
        moveButton: "移動",
        copyButton: "拷貝",
        moveMessage: "選擇要將所選項目移動到的位置。",
        copyMessage: "選擇要將所選項目拷貝到的位置。",
        deleteTitle: "要永久刪除嗎？",
        deleteBodyFormat: "%@ 將立即刪除，不會移到垃圾桶。此動作無法還原。",
        deleteButton: "刪除",
        cancel: "取消",
        featureOffFormat: "請先在 PowerTools 中開啟「%@」",
        renameTitle: "批次重新命名",
        renameFind: "尋找",
        renameReplace: "取代為",
        renamePrefix: "加在名稱前",
        renameSuffix: "加在名稱後",
        renameNumbers: "加入編號",
        renameStart: "起始編號",
        renameButton: "重新命名",
        renameInvalid: "名稱不可為空白，也不可包含 / 或 :。",
        renameDuplicate: "兩個項目會使用相同的名稱。",
        renameTaken: "資料夾中已有同名項目。"
    )
}
